### ISSUE TITLE
Java and C++ 

### ISSUE THREAD

**Issue by ratemoclinton** [RHyde67/DDC-Python#1]
Do you have DDC for Java and C+++

**Comment by RHyde67** [comment]
Sorry, I don't.
One of my students did try and port it to C++ and I have the code. I have no idea if it works or not, but it might be helpful to start you off if you would like it?

Cheers,
Rich

**Comment by ratemoclinton** [comment]
kindly send me the c++ code

**Comment by ratemoclinton** [comment]
Also can you give me a brief summary how this python ddc works, will appreciate.

**Comment by ratemoclinton** [comment]
Professor Rich kindly send me the c++ code here or you can send it at my email at ratemouniverse@gmail.com also if there is an explanation with it, specifications please do share

**Comment by ratemoclinton** [comment]
Professor Rich kindly send me the c++ code here or you can send it at my email at ratemouniverse@gmail.com also if there is an explanation with it, specifications please do share

**Comment by RHyde67** [comment]
I tried emailing it, but it got rejected as it had code attached, so I'll create a repo later.
There's no documentation with it unfortunately, he just did it for fun really.
Cheers,
Rich

**Comment by RHyde67** [comment]
I've created a private repo and invited you.
It turns out it's C#, not C++, hope it's still useful.
Cheers,
Rich

**Comment by ratemoclinton** [comment]
Thanks got the email so there is nobody who has for java and c++ hehe

**Comment by ratemoclinton** [comment]
Page not found on repository

**Comment by RHyde67** [comment]
It says waiting for your response to invite. It's a private repo, only you and me at the moment.

**Comment by ratemoclinton** [comment]
Try  resending because i opened several times not having luck lol

**Comment by RHyde67** [comment]
Resent.

**Comment by ratemoclinton** [comment]
Got it, apparantely it opened on a browser which i hadnt logged in so thats why the error. Thanks Professor keep up the good work with students lol
